# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/Vivado/Assignment_2/Assignment_2.srcs/sources_1/ip/xbip_multadd_0/xbip_multadd_0.xci
# IP: The module: 'xbip_multadd_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Vivado/Assignment_2/Assignment_2.srcs/sources_1/ip/xbip_multadd_0/xbip_multadd_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_multadd_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Projects/Vivado/Assignment_2/Assignment_2.srcs/sources_1/ip/xbip_multadd_0/xbip_multadd_0.xci
# IP: The module: 'xbip_multadd_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Vivado/Assignment_2/Assignment_2.srcs/sources_1/ip/xbip_multadd_0/xbip_multadd_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_multadd_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
